name: Autoformat code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        mkdir temp
        cd temp
        wget https://download-cf.jetbrains.com/python/pycharm-professional-2020.2.3.tar.gz
        tar -xvf pycharm-professional-2020.2.3.tar.gz
        cd ../../
    - name: Setup git
      run: |         
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
    - name: Cleanup code
      run: |
        source temp/pycharm-2020.2.3/bin/pycharm.sh format -r ./
        rm -rf temp/
        git add .
        git commit -m "Auto: Format files"
        git push
